default:
  psi_grid:
    step_size: 0.01
    num_std_errors: 
      - -3
      - 3
  omega_hat_specs:
    init_guess_sd: 0.1
    threshold: 
  parallel_specs:
    num_workers: 12
    chunk_size: 5
  output_dir: "results"