experiment_id: experiment_A
seed: 7835
X1_levels:
  A:
    X2:
      dist:
        name: rbeta
        params:
        - 2.0
        - 5.0
      support:
      - 0.0
      - 1.0
      entropy_range:
      - 1.2149963
      - 1.5379362
    ref_level: yes
    level_of_interest: yes
  B:
    X2:
      dist:
        name: rbeta
        params:
        - 3.0
        - 3.0
      support:
      - 0.0
      - 1.0
      entropy_range:
      - 0.7844098
      - 1.1073497
    ref_level: no
    level_of_interest: no
  C:
    X2:
      dist:
        name: rbeta
        params:
        - 5.0
        - 2.0
      support:
      - 0.0
      - 1.0
      entropy_range:
      - 0.3538233
      - 0.6767632
    ref_level: no
    level_of_interest: no
true_param_specs:
  J: 6
  entropy_range_specs:
    offset:
    - 0.3
    - 0.2
    padding: 0.75
  num_X2_test_vals: 1000
  p: 6
Beta_0_path: results/experiment_A/Beta_0.rds
