default:
  X1_specs:
    X1_levels:
      base_X2: &base_X2
        specs: &base_X2_specs
          dist:
            name:  # to be set per level
            params: []  # to be set per level
          interval:  # to be set per level
        values: []

      A:
        num_obs: 60
        X2:
          <<: *base_X2
          specs:
            <<: *base_X2_specs
            dist:
              name: rbeta
              params: [2, 5]
            interval: [0, 1]
        ref_level: true
        level_of_interest: true

      B:
        num_obs: 60
        X2:
          <<: *base_X2
          specs:
            <<: *base_X2_specs
            dist:
              name: rbeta
              params: [3, 3]
            interval: [0, 1]
        ref_level: false
        level_of_interest: false

      C:
        num_obs: 60
        X2:
          <<: *base_X2
          specs:
            <<: *base_X2_specs
            dist:
              name: rbeta
              params: [5, 2]
            interval: [0, 1]
        ref_level: false
        level_of_interest: false

  data:
    formula: Y ~ .^2 - 1
