IL:
  step_size: 0.01
  fine_step_size: 0.005
  fine_window: 0.05
  num_std_errors: 3
  init_guess_sd: 10
  threshold_offset: 20
  chunk_size: 1
PL: 
  step_size: 0.01
  fine_step_size: 0.005
  fine_window: 0.05
  alpha: 0.05

