IL:
  step_size: 0.05
  fine_step_size: 0.01
  fine_window: 0.03
  num_std_errors: 3.5
  init_guess_sd: 10
  threshold_offset: 20
  chunk_size: 1
PL: 
  step_size: 0.05
  fine_step_size: 0.01
  fine_window: 0.03
  alpha: 0.05

