default:
  X1_levels:
    A:
      num_obs: 60
      X2_interval:
        - 0
        - 1
      X2_shape_params:
        - 2
        - 5
      ref_level: TRUE
      level_of_interest: TRUE
    B:
      num_obs: 60
      X2_interval:
        - 0
        - 1
      X2_shape_params:
        - 3
        - 3
      ref_level: FALSE
      level_of_interest: FALSE
    C:
      num_obs: 60
      X2_interval:
        - 0
        - 1
      X2_shape_params:
        - 5
        - 2
      ref_level: FALSE
      level_of_interest: FALSE
  data:
    J: 6
    "n":
    formula: Y ~ .^2 - 1