seed: 7835
X1_levels:
  A:
    X2:
      dist:
        name: rbeta
        params: [2, 5]
      support: [0, 1]
    m: 60
    ref_level: true
    level_of_interest: true
  B:
    X2:
      dist:
        name: rbeta
        params: [3, 3]
      support: [0, 1]
    m: 60
    ref_level: false
    level_of_interest: false
  C:
    X2:
      dist:
        name: rbeta
        params: [5, 2]
      support: [0, 1]
    m: 60
    ref_level: false
    level_of_interest: false
model_specs:
  J: 6
  entropy_range_specs:
    offset: [0.3, 0.2]
    padding: 0.75
  reps:
    Beta_0: 1000
    pY_0: 1000000
  formula: "~.^2 - 1"
optimization_specs:
  step_size: 0.01
  num_std_errors: 3.5
  init_guess_sd: 5
  threshold_offset: 20
  chunk_size: 1
  maxtime:
    IL: 10
    PL: 10
  

  