# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterate_while_1 <- function(psi_max, branch_max, initial_guess, get_Beta_hat, get_log_likelihood, omega_hat, X_one_hot, X_h_one_hot, Y_one_hot, crit, step_size, max_psi_val, verbose) {
    .Call(`_iterate_iterate_while_1`, psi_max, branch_max, initial_guess, get_Beta_hat, get_log_likelihood, omega_hat, X_one_hot, X_h_one_hot, Y_one_hot, crit, step_size, max_psi_val, verbose)
}

iterate_while_2 <- function(psi_max, branch_max, initial_guess, get_Beta_hat, get_log_likelihood, omega_hat, X_one_hot, X_h_one_hot, Y_one_hot, crit, step_size, max_psi_val, verbose) {
    .Call(`_iterate_iterate_while_2`, psi_max, branch_max, initial_guess, get_Beta_hat, get_log_likelihood, omega_hat, X_one_hot, X_h_one_hot, Y_one_hot, crit, step_size, max_psi_val, verbose)
}

