# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterate_over <- function(iteration_values, initial_guess, custom_function, args, fill_bottom_to_top = FALSE) {
    .Call(`_iterate_iterate_over`, iteration_values, initial_guess, custom_function, args, fill_bottom_to_top)
}

rcpp_hello_world <- function() {
    .Call(`_iterate_rcpp_hello_world`)
}

