default:
  lambda_grid:
    interval:
      start: -5
    step_size: 0.1
    epsilon: 0.001
  psi_grid:
    step_size: 0.01
    num_std_errors: 
      - -3
      - 3
  parallel_specs:
    num_workers: 12
    chunk_size: 5
  output_dir: "results"