default: 
  seed: 9565
  shared_args:
    "n": 30
  theta_0:
    dist: 
      name: "runif"
      args:
        min: 3
        max: 10
      avg: FALSE
  weights:
    dist: 
      name: "runif"
      args:
        min: 0
        max: 1
      avg: 1

  