# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accumulate_rcpp <- function(x, f, init) {
    .Call(`_accumulate_accumulate_rcpp`, x, f, init)
}

rcpp_hello_world <- function() {
    .Call(`_accumulate_rcpp_hello_world`)
}

