---
title: "Simulation Report"
format: 
  html:
    embed-resources: true
params:
  experiment: null
  X1_levels: null
  model_specs: null
  optimization_specs: null
---

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
library(here)
library(yaml)

proj_subdir <- here("Integrated_Likelihood_Algorithm", "Polytomous_Logistic_Regression")
proj_path <- function(...) here(proj_subdir, ...)
miceadds::source.all(proj_path("scripts", "helpers"), print.source = FALSE)

list2env(params, envir = environment())
experiment_id <- experiment$id
sim_id <- experiment$sim_id
exp_dir <- proj_path("experiments", experiment_id)
sim_dir <- here(exp_dir, "simulations", sim_id)
run_dirs <- list.dirs(sim_dir, recursive = FALSE)
true_params_dir <- proj_path("experiments", experiment_id, "true_params")
```

```{r}
H_0 <- readRDS(here(true_params_dir, "H_0.rds"))
h <- get_X1_level_of_interest(X1_levels)
psi_0 <- H_0 |>
  filter(X1 == h) |>
  pull(entropy)
```

```{r}
MLE_data_list <- run_dirs |>
  map(\(run_dir) MLE_data <- readRDS(here(run_dir, "results", "MLE_data.rds")))

summarize_mle_performance(MLE_data_list, psi_0)
```

```{r}
conf_ints_list <- run_dirs |>
  map(\(run_dir) readRDS(here(run_dir, "results", "conf_ints.rds")))

summarize_confidence_intervals(conf_ints_list, psi_0)
```




