---
format: 
  pdf:
    documentclass: nuthesis
    classoption: ["reqno"]
    number-sections: true
    number-depth: 3
bibliography: ./files/lit_review.bib
csl: ./files/apa.csl 
link-citations: true  
indent: true
header-includes: 
    - \numberwithin{equation}{section}
    - \usepackage{indentfirst}
    - \usepackage{enumitem}
    - \usepackage{unicode-math}
    - \usepackage{mathrsfs}
    - \usepackage{amsmath}
    - \usepackage{bbm}
---

<!-- Front matter: title page, abstract, acknowledgements, table of contents,... -->
```{r}
#| child = './files/front_matter.qmd'
``` 

<!-- Dissertation body -->
```{r}
#| child = './files/Chapter1.qmd'
```

```{r}
#| child = './files/Chapter2.qmd'
```

```{r}
#| child = './files/Chapter3.qmd'
```

```{r}
#| child = './files/Chapter4.qmd'
```

```{r}
#| child = './files/Chapter5.qmd'
```

```{r}
#| child = './files/Chapter6.qmd'
```

```{r}
#| child = './files/Chapter7.qmd'
```

```{r}
#| child = './files/Chapter8.qmd'
```

```{r}
#| child = './files/Chapter9.qmd'
```

\clearpage

<!-- References -->
\chapter*{References} 

::: {#refs}
:::

<!-- Appendix -->
```{r} 
#| child = './files/Appendix.qmd'
```



