# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowLogSumExps_rcpp <- function(Y_hat) {
    .Call(`_PolytomousUtils_rowLogSumExps_rcpp`, Y_hat)
}

log_likelihood_rcpp <- function(Beta, X_one_hot, Y_one_hot, Jm1, p, n) {
    .Call(`_PolytomousUtils_log_likelihood_rcpp`, Beta, X_one_hot, Y_one_hot, Jm1, p, n)
}

softmax_adj_vector_rcpp <- function(x) {
    .Call(`_PolytomousUtils_softmax_adj_vector_rcpp`, x)
}

softmax_adj_matrix_rcpp <- function(x) {
    .Call(`_PolytomousUtils_softmax_adj_matrix_rcpp`, x)
}

softmax_vector_rcpp <- function(x) {
    .Call(`_PolytomousUtils_softmax_vector_rcpp`, x)
}

softmax_matrix_rcpp <- function(x) {
    .Call(`_PolytomousUtils_softmax_matrix_rcpp`, x)
}

PoI_fn_rcpp <- function(Beta, X_h_one_hot) {
    .Call(`_PolytomousUtils_PoI_fn_rcpp`, Beta, X_h_one_hot)
}

Beta_hat_obj_fn_rcpp <- function(Beta, X_one_hot, omega_hat, lambda, Jm1, p, n) {
    .Call(`_PolytomousUtils_Beta_hat_obj_fn_rcpp`, Beta, X_one_hot, omega_hat, lambda, Jm1, p, n)
}

Beta_hat_con_fn_rcpp <- function(Beta, X_h_one_hot, psi, Jm1, p) {
    .Call(`_PolytomousUtils_Beta_hat_con_fn_rcpp`, Beta, X_h_one_hot, psi, Jm1, p)
}

omega_hat_obj_fn_rcpp <- function(Beta, X_h_one_hot, Jm1, p, psi_hat) {
    .Call(`_PolytomousUtils_omega_hat_obj_fn_rcpp`, Beta, X_h_one_hot, Jm1, p, psi_hat)
}

omega_hat_eq_con_fn_rcpp <- function(Beta, X_h_one_hot, Jm1, p, psi_hat) {
    .Call(`_PolytomousUtils_omega_hat_eq_con_fn_rcpp`, Beta, X_h_one_hot, Jm1, p, psi_hat)
}

omega_hat_ineq_con_fn_rcpp <- function(Beta, X_one_hot, Y_one_hot, Jm1, p, n, threshold) {
    .Call(`_PolytomousUtils_omega_hat_ineq_con_fn_rcpp`, Beta, X_one_hot, Y_one_hot, Jm1, p, n, threshold)
}

